export const servicesData = {
  ftl: {
    slug: 'ftl',
    title: 'Full Truck Load (FTL)',
    shortTitle: 'FTL Services',
    description: 'Dedicated full truck shipments for large consignments with door-to-door delivery across India. Ideal for bulk cargo requiring exclusive vehicle allocation.',
    heroSubtitle: 'Dedicated full truck shipments with guaranteed transit times, real-time GPS tracking, and door-to-door delivery across all 28 states of India.',
    features: [
      'Dedicated vehicle for your exclusive shipment',
      'Door-to-door pickup and delivery',
      'Real-time GPS tracking and ETAs',
      'All vehicle types: Mini trucks to multi-axle',
      'Express, standard, and economy options',
      'Scheduled and on-demand bookings',
      'Insurance coverage for all shipments',
      'Professional and verified drivers',
    ],
    benefits: [
      { title: 'Faster Transit', description: 'No intermediate stops or hub transfers. Direct routes mean shorter delivery times.' },
      { title: 'Zero Damage Risk', description: 'Single shipper per vehicle eliminates handling damage from co-loading.' },
      { title: 'Flexible Scheduling', description: 'Book same-day, next-day, or scheduled pickups based on your production cycles.' },
      { title: 'Complete Visibility', description: 'Real-time GPS tracking, milestone alerts, and dedicated point of contact throughout transit.' },
    ],
    idealFor: [
      'Bulk raw material shipments',
      'Factory-to-warehouse transfers',
      'Inter-state distribution',
      'Time-sensitive deliveries',
      'High-value goods requiring exclusive handling',
      'Oversized or heavy cargo',
    ],
    stats: [
      { value: '5000+', label: 'FTL Trips/Month' },
      { value: '98%', label: 'On-Time Rate' },
      { value: '500+', label: 'Routes Covered' },
      { value: '24h', label: 'Avg. Response Time' },
    ],
  },
  ptl: {
    slug: 'ptl',
    title: 'Part Truck Load (PTL)',
    shortTitle: 'PTL Services',
    description: 'Cost-effective shared transport for smaller loads. Consolidate your shipments for maximum savings with reliable transit times.',
    heroSubtitle: 'Smart shared transportation for shipments under full truck capacity. Save up to 40% on logistics costs with guaranteed delivery schedules.',
    features: [
      'Cost-effective for 100 kg to 5000 kg shipments',
      'Hub-to-hub and door-to-door options',
      'Scheduled departures from major routes',
      'Consolidated with compatible cargo only',
      'Tracking via unique consignment number',
      'Competitive rates with volume discounts',
      'Safe handling with systematic loading',
      'Insurance available for all consignments',
    ],
    benefits: [
      { title: 'Up to 40% Cost Savings', description: 'Share truck capacity with other shippers. Pay only for space you use.' },
      { title: 'Regular Scheduled Services', description: 'Daily and weekly departures on major routes ensure predictable delivery.' },
      { title: 'No Minimum Commitment', description: 'Ship as little as 100 kg per consignment. No long-term contracts required.' },
      { title: 'Wide Network', description: 'PTL services across 500+ cities with hub connectivity for last-mile delivery.' },
    ],
    idealFor: [
      'Small to medium consignments (100 kg – 5 tons)',
      'Regular distribution to multiple locations',
      'E-commerce seller shipments',
      'Spare parts and aftermarket goods',
      'Sample dispatches and trial orders',
      'SME and startup logistics needs',
    ],
    stats: [
      { value: '8000+', label: 'PTL Shipments/Month' },
      { value: '40%', label: 'Cost Savings' },
      { value: '500+', label: 'Cities Connected' },
      { value: '3-5 Days', label: 'Pan India Transit' },
    ],
  },
  warehousing: {
    slug: 'warehousing',
    title: 'Warehousing Solutions',
    shortTitle: 'Warehousing',
    description: 'Secure, modern warehousing facilities with inventory management, order fulfillment, and value-added services at strategic locations.',
    heroSubtitle: 'State-of-the-art warehousing facilities with advanced inventory management, seamless order fulfillment, and strategic locations for faster distribution.',
    features: [
      'Secure and surveillance-monitored facilities',
      'Climate-controlled storage available',
      'Advanced inventory management system',
      'Pick, pack, and dispatch services',
      'Cross-docking and break-bulk operations',
      'Quality inspection and labeling',
      'FIFO/LIFO inventory rotation',
      'Real-time stock visibility via dashboard',
    ],
    benefits: [
      { title: 'Reduced Capital Investment', description: 'No need to own warehouse infrastructure. Pay only for space and services you use.' },
      { title: 'Strategic Locations', description: 'Warehouses near major highways and markets for faster distribution reach.' },
      { title: 'Scalable Space', description: 'Scale up or down based on seasonal demand. Flexible contracts from 1 month.' },
      { title: 'Integrated Distribution', description: 'Seamless connection to our FTL, PTL, and last-mile delivery network.' },
    ],
    idealFor: [
      'Distribution center operations',
      'E-commerce fulfillment and storage',
      'Seasonal inventory overflow',
      'Buffer stock management',
      'Hub-and-spoke distribution models',
      'Cross-docking for fast-moving goods',
    ],
    stats: [
      { value: '50,000+', label: 'Sq. Ft. Capacity' },
      { value: '99.5%', label: 'Inventory Accuracy' },
      { value: '24/7', label: 'CCTV Surveillance' },
      { value: '4h', label: 'Order Processing' },
    ],
  },
  distribution: {
    slug: 'distribution',
    title: 'Distribution Services',
    shortTitle: 'Distribution',
    description: 'End-to-end product distribution with route optimization, multi-point deliveries, and real-time tracking for complete supply chain visibility.',
    heroSubtitle: 'Complete distribution management from factory gate to retail shelf. Multi-point deliveries, route optimization, and real-time visibility for seamless supply chains.',
    features: [
      'Multi-point delivery with route optimization',
      'Scheduled and recurring distribution runs',
      'Retail and wholesale distribution',
      'Proof of delivery with digital POD',
      'Returns and reverse logistics management',
      'Dedicated distribution fleet options',
      'Real-time delivery tracking and alerts',
      'Monthly MIS reports and analytics',
    ],
    benefits: [
      { title: 'Faster Market Reach', description: 'Optimized distribution networks ensure your products reach customers faster than competition.' },
      { title: 'Lower Distribution Costs', description: 'Route optimization and load consolidation reduce per-unit distribution costs significantly.' },
      { title: 'Better Fill Rates', description: 'Reliable schedules and buffer planning ensure higher shelf availability for your products.' },
      { title: 'Complete Transparency', description: 'Digital POD, real-time tracking, and monthly analytics for full supply chain visibility.' },
    ],
    idealFor: [
      'FMCG retail distribution',
      'Pharmacy and healthcare distribution',
      'Multi-brand distributor operations',
      'Factory-to-dealer networks',
      'Institutional and bulk deliveries',
      'E-commerce marketplace deliveries',
    ],
    stats: [
      { value: '2000+', label: 'Delivery Points/Day' },
      { value: '95%', label: 'Fill Rate' },
      { value: '200+', label: 'Distribution Routes' },
      { value: '<2%', label: 'Damage Rate' },
    ],
  },
  'dedicated-fleet': {
    slug: 'dedicated-fleet',
    title: 'Dedicated Fleet Services',
    shortTitle: 'Dedicated Fleet',
    description: 'Exclusive fleet deployed for your business operations with customized vehicles, dedicated drivers, and full operational control.',
    heroSubtitle: 'Your exclusive fleet, our management expertise. Customized vehicles, professional drivers, and complete operational control without capital investment.',
    features: [
      'Exclusively assigned vehicles for your business',
      'Dedicated trained drivers and crew',
      'Full fleet management and maintenance',
      'Customized vehicle branding available',
      'GPS tracking and telematics integration',
      'Monthly reporting and fleet analytics',
      'Compliance and documentation management',
      'Backup vehicle guarantee for zero downtime',
    ],
    benefits: [
      { title: 'Zero Capital Investment', description: 'Get a dedicated fleet without buying vehicles. We handle acquisition, maintenance, and depreciation.' },
      { title: 'Operational Control', description: 'Your routes, your schedule, your priorities – with our fleet management expertise backing it up.' },
      { title: '100% Availability', description: 'Backup vehicle guarantee ensures zero downtime. Your operations never stop.' },
      { title: 'Cost Predictability', description: 'Fixed monthly costs with no surprises. Budget your logistics with confidence.' },
    ],
    idealFor: [
      'Manufacturing plant logistics',
      'Daily distribution runs',
      'E-commerce dedicated deliveries',
      'Retail chain replenishment',
      'Corporate employee transportation',
      'Project-based logistics requirements',
    ],
    stats: [
      { value: '100+', label: 'Dedicated Contracts' },
      { value: '100%', label: 'Uptime Guarantee' },
      { value: '0', label: 'Capital Required' },
      { value: '30%', label: 'Cost Reduction' },
    ],
  },
  'supply-chain': {
    slug: 'supply-chain',
    title: 'Supply Chain Management',
    shortTitle: 'Supply Chain',
    description: 'Comprehensive supply chain optimization from sourcing to delivery. Reduce costs, improve efficiency, and gain competitive advantage.',
    heroSubtitle: 'End-to-end supply chain design, implementation, and management. From procurement logistics to final delivery, we optimize every link in your chain.',
    features: [
      'Supply chain design and consulting',
      'Vendor management and inbound logistics',
      'Inventory optimization and planning',
      'Multi-modal transportation management',
      'Technology integration and visibility platforms',
      'Performance analytics and KPI tracking',
      'Risk management and contingency planning',
      'Continuous improvement programs',
    ],
    benefits: [
      { title: 'Total Cost Reduction', description: 'Holistic supply chain optimization can reduce total logistics costs by 15-25% through efficiency gains.' },
      { title: 'Improved Service Levels', description: 'Better planning, faster transit, and reliable delivery improve your customer satisfaction scores.' },
      { title: 'Scalable Solutions', description: 'Supply chain designed to grow with your business. Flexible capacity for seasonal peaks.' },
      { title: 'Single Point of Contact', description: 'One partner managing your entire supply chain means fewer vendors, less complexity, better coordination.' },
    ],
    idealFor: [
      'Companies looking to outsource logistics',
      'Businesses scaling across new geographies',
      'Organizations seeking cost reduction',
      'Complex multi-location supply chains',
      'Companies with seasonal demand fluctuations',
      'New market entry logistics planning',
    ],
    stats: [
      { value: '20%', label: 'Avg. Cost Reduction' },
      { value: '50+', label: 'SCM Clients' },
      { value: '99%', label: 'SLA Compliance' },
      { value: '360°', label: 'Visibility' },
    ],
  },
  'last-mile': {
    slug: 'last-mile',
    title: 'Last Mile Delivery',
    shortTitle: 'Last Mile',
    description: 'Reliable last mile delivery solutions ensuring products reach end customers on time with proof of delivery and real-time updates.',
    heroSubtitle: 'The final and most critical leg of delivery. Our last-mile network ensures your products reach end customers reliably, on time, with complete proof of delivery.',
    features: [
      'Doorstep delivery across 500+ cities',
      'Same-day and next-day delivery options',
      'Digital proof of delivery (ePOD)',
      'Cash on delivery (COD) handling',
      'Delivery attempt management and reschedule',
      'Customer communication via SMS/WhatsApp',
      'Returns pickup and reverse logistics',
      'Delivery slot selection for customers',
    ],
    benefits: [
      { title: 'Higher Delivery Success', description: 'Trained delivery staff and smart routing achieve 95%+ first-attempt delivery success.' },
      { title: 'Customer Satisfaction', description: 'Real-time updates, delivery slots, and professional handling improve end-customer experience.' },
      { title: 'Cost per Delivery Optimization', description: 'Route density planning and multi-drop optimization reduce per-delivery costs.' },
      { title: 'Flexible Payment Collection', description: 'COD, digital payments, and prepaid – we handle all payment modes at doorstep.' },
    ],
    idealFor: [
      'E-commerce order deliveries',
      'D2C brand fulfillment',
      'Subscription box deliveries',
      'Document and parcel deliveries',
      'Food and grocery delivery',
      'Furniture and appliance delivery',
    ],
    stats: [
      { value: '500+', label: 'Cities Covered' },
      { value: '95%', label: 'First Attempt Success' },
      { value: '10K+', label: 'Deliveries/Day' },
      { value: '<48h', label: 'Avg. Delivery Time' },
    ],
  },
  ecommerce: {
    slug: 'ecommerce',
    title: 'E-Commerce Logistics',
    shortTitle: 'E-Commerce',
    description: 'Specialized fulfillment for online businesses including pick-pack-ship, returns management, and COD handling across India.',
    heroSubtitle: 'Complete e-commerce logistics stack: warehousing, fulfillment, shipping, last-mile delivery, and returns management – all under one roof.',
    features: [
      'Multi-channel order management integration',
      'Pick, pack, and ship operations',
      'Same-day dispatch for orders before cutoff',
      'Multi-carrier shipping with best rate selection',
      'Returns processing and restocking',
      'COD reconciliation and remittance',
      'Branded packaging options',
      'Real-time inventory sync across channels',
    ],
    benefits: [
      { title: 'Faster Order Fulfillment', description: 'Same-day dispatch for orders placed before 2 PM. Reduce delivery time by 1-2 days.' },
      { title: 'Lower RTO Rates', description: 'Address verification, customer confirmation, and smart delivery reduce return-to-origin rates.' },
      { title: 'Scalable Operations', description: 'Handle 100 or 10,000 orders per day with the same efficiency. No hiring headaches.' },
      { title: 'Multi-Platform Integration', description: 'Seamless integration with Shopify, WooCommerce, Amazon, Flipkart, and other marketplaces.' },
    ],
    idealFor: [
      'D2C brands and online stores',
      'Amazon and Flipkart sellers',
      'Shopify and WooCommerce merchants',
      'Subscription commerce businesses',
      'Social commerce sellers',
      'Crowdfunding fulfillment',
    ],
    stats: [
      { value: '50K+', label: 'Orders/Month' },
      { value: '99.5%', label: 'Order Accuracy' },
      { value: '<4h', label: 'Dispatch Time' },
      { value: '15%', label: 'Lower RTO' },
    ],
  },
  'express-cargo': {
    slug: 'express-cargo',
    title: 'Express Cargo Services',
    shortTitle: 'Express Cargo',
    description: 'Time-critical express deliveries with guaranteed transit times. Next-day and same-day delivery options for urgent shipments.',
    heroSubtitle: 'When time is everything. Guaranteed express delivery with same-day, next-day, and time-definite options for your most urgent shipments.',
    features: [
      'Same-day delivery within city limits',
      'Next-day inter-city express',
      'Time-definite guaranteed delivery',
      'Priority handling and loading',
      'Dedicated express routes',
      'Real-time tracking with live ETAs',
      'Proof of delivery within minutes',
      'Money-back guarantee for delays',
    ],
    benefits: [
      { title: 'Guaranteed Timelines', description: 'Time-definite delivery with money-back guarantee if we miss the committed timeline.' },
      { title: 'Priority Handling', description: 'Express shipments get priority loading, dedicated routes, and expedited processing at hubs.' },
      { title: 'Minimal Documentation', description: 'Quick booking, instant tracking ID, and hassle-free pickup for time-sensitive cargo.' },
      { title: 'Premium Support', description: 'Dedicated express helpline with real-time updates and proactive delay communication.' },
    ],
    idealFor: [
      'Urgent spare parts delivery',
      'Time-critical documents and samples',
      'Emergency production materials',
      'Medical and pharmaceutical urgencies',
      'Event and exhibition logistics',
      'High-priority client shipments',
    ],
    stats: [
      { value: '99%', label: 'On-Time Delivery' },
      { value: '6h', label: 'Same-City Express' },
      { value: '24h', label: 'Inter-City Express' },
      { value: '1000+', label: 'Express Routes' },
    ],
  },
} as const;

export type ServiceSlug = keyof typeof servicesData;
